server:
  port: 80


spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 192.168.70.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}