server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7001/eureka

ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug